Add symbol method for NA.
I needed to define this for a case like this:

```julia
julia> using DataFrames

julia> df = DataFrame(Test = @data ["a", NA, "c"])
3x1 DataFrame
| Row | Test |
|-----|------|
| 1   | "a"  |
| 2   | NA   |
| 3   | "c"  |

julia> test = countmap(df[:Test])
Dict{Union(NAtype,ASCIIString),Int64} with 3 entries:
  "c" => 1
  NA  => 1
  "a" => 1

julia> test_count = DataFrame(;[symbol(k) => v for (k, v) in test]...)
ERROR: `symbol` has no method matching symbol(::NAtype)
 in anonymous at no file

julia> Base.symbol(x::NAtype) = :NA
symbol (generic function with 7 methods)

julia> test_count = DataFrame(;[symbol(k) => v for (k, v) in test]...)
1x3 DataFrame
| Row | NA | c | a |
|-----|----|---|---|
| 1   | 1  | 1 | 1 |
```